dbfilename redis_queue.rdb
dir /home/erpnext/benches/ifran_cabs/config/pids
pidfile /home/erpnext/benches/ifran_cabs/config/pids/redis_queue.pid
bind 127.0.0.1
port 11001

aclfile /home/erpnext/benches/ifran_cabs/config/redis_queue.acl
